name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: dev1-500309
  REGION: us-central1
  REPOSITORY: app-repo
  IMAGE_NAME: demo-app
  SERVICE_NAME: demo-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/488062594749/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: my-project-dev@dev1-500309.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Image
        run: docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
